version: '3.4'

services:
  assets:
    image: assets
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6565:6565"
    volumes:
      - /var/www/assets:/app/assets
      - ./database:/app/database
    environment:
      - SECRET_KEY=<SECRET_KEY>
      - SIGNUP=True
    
    restart: always